import { SiteColors } from './types';

export const HARMONIC_PALETTES: SiteColors[] = [
  {
    id: 'emerald-luxe',
    name: '1. Esmeralda Vital',
    primary: '#059669',
    secondary: '#10B981',
    background: '#F0FDF4',
    cardBg: '#FFFFFF',
    text: '#064E3B',
    textMuted: '#047857',
    accent: '#F59E0B',
  },
  {
    id: 'ocean-breeze',
    name: '2. Brisa Oceánica',
    primary: '#2563EB',
    secondary: '#3B82F6',
    background: '#EFF6FF',
    cardBg: '#FFFFFF',
    text: '#1E3A8A',
    textMuted: '#1D4ED8',
    accent: '#EC4899',
  },
  {
    id: 'sunset-amber',
    name: '3. Cálido Atardecer',
    primary: '#D97706',
    secondary: '#F59E0B',
    background: '#FFFBEB',
    cardBg: '#FFFFFF',
    text: '#78350F',
    textMuted: '#B45309',
    accent: '#10B981',
  },
  {
    id: 'minimal-dark',
    name: '4. Cyber Minimal',
    primary: '#6366F1',
    secondary: '#818CF8',
    background: '#0F172A',
    cardBg: '#1E293B',
    text: '#F8FAFC',
    textMuted: '#94A3B8',
    accent: '#22C55E',
  },
  {
    id: 'rose-pastel',
    name: '5. Rosa Elegante',
    primary: '#E11D48',
    secondary: '#F43F5E',
    background: '#FFF1F2',
    cardBg: '#FFFFFF',
    text: '#881337',
    textMuted: '#BE123C',
    accent: '#8B5CF6',
  },
  {
    id: 'clean-mono',
    name: '6. Blanco & Negro Pro',
    primary: '#18181B',
    secondary: '#3F3F46',
    background: '#FAFAFA',
    cardBg: '#FFFFFF',
    text: '#09090B',
    textMuted: '#52525B',
    accent: '#2563EB',
  },
  {
    id: 'nordic-ice',
    name: '7. ❄️ Nórdico Hielo',
    primary: '#0284C7',
    secondary: '#38BDF8',
    background: '#F0F9FF',
    cardBg: '#FFFFFF',
    text: '#0C4A6E',
    textMuted: '#0369A1',
    accent: '#F43F5E',
  },
  {
    id: 'lavender-dream',
    name: '8. 🪻 Lavanda Pastel',
    primary: '#7C3AED',
    secondary: '#A78BFA',
    background: '#F5F3FF',
    cardBg: '#FFFFFF',
    text: '#4C1D95',
    textMuted: '#6D28D9',
    accent: '#10B981',
  },
  {
    id: 'terracotta-warm',
    name: '9. 🧱 Terracota Cálido',
    primary: '#C2410C',
    secondary: '#EA580C',
    background: '#FFF7ED',
    cardBg: '#FFFFFF',
    text: '#7C2D12',
    textMuted: '#9A3412',
    accent: '#0284C7',
  },
  {
    id: 'electric-neon',
    name: '10. ⚡ Neón Eléctrico',
    primary: '#06B6D4',
    secondary: '#22D3EE',
    background: '#042F2E',
    cardBg: '#115E59',
    text: '#CCFBF1',
    textMuted: '#5EEAD4',
    accent: '#F43F5E',
  },
  {
    id: 'forest-sage',
    name: '11. 🌲 Bosque Sabia',
    primary: '#15803D',
    secondary: '#4ADE80',
    background: '#F0FDF4',
    cardBg: '#FFFFFF',
    text: '#14532D',
    textMuted: '#166534',
    accent: '#D97706',
  },
  {
    id: 'coffee-caramel',
    name: '12. ☕ Caramelo & Café',
    primary: '#78350F',
    secondary: '#92400E',
    background: '#FEF3C7',
    cardBg: '#FFFFFF',
    text: '#451A03',
    textMuted: '#B45309',
    accent: '#059669',
  },
  {
    id: 'golden-luxury',
    name: '13. 👑 Dorado Lujo',
    primary: '#B45309',
    secondary: '#F59E0B',
    background: '#18181B',
    cardBg: '#27272A',
    text: '#FDE68A',
    textMuted: '#F59E0B',
    accent: '#EC4899',
  },
  {
    id: 'cyber-violet',
    name: '14. 🌆 Cyberpunk Violeta',
    primary: '#D946EF',
    secondary: '#E879F9',
    background: '#2E1065',
    cardBg: '#3B0764',
    text: '#F5D0FE',
    textMuted: '#C084FC',
    accent: '#22D3EE',
  },
  {
    id: 'peach-sunset',
    name: '15. 🍑 Atardecer Melocotón',
    primary: '#F97316',
    secondary: '#FB923C',
    background: '#FFF7ED',
    cardBg: '#FFFFFF',
    text: '#7C2D12',
    textMuted: '#EA580C',
    accent: '#8B5CF6',
  },
  {
    id: 'corporate-blue',
    name: '16. 💼 Azul Corporativo Pro',
    primary: '#1E40AF',
    secondary: '#3B82F6',
    background: '#F8FAFC',
    cardBg: '#FFFFFF',
    text: '#1E293B',
    textMuted: '#475569',
    accent: '#10B981',
  },
];

export function getPalette(id: string): SiteColors {
  return HARMONIC_PALETTES.find((p) => p.id === id) || HARMONIC_PALETTES[0];
}

export function getContrastColor(hexColor: string): string {
  const hex = hexColor.replace('#', '');
  const r = parseInt(hex.substring(0, 2), 16) || 0;
  const g = parseInt(hex.substring(2, 4), 16) || 0;
  const b = parseInt(hex.substring(4, 6), 16) || 0;
  const yiq = (r * 299 + g * 587 + b * 114) / 1000;
  return yiq >= 128 ? '#0F172A' : '#FFFFFF';
}
